services:
  postgres:
    build: ./postgres
    container_name: postgres_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@my-app.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_DISABLE_POSTFIX=true
    ports:
      - '5051:80'
    volumes:
      - ./pgadmin4/pgadmin:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
